<h3>에러 처리</h3>

- try...catch 문을 사용해서 에러에 적절히 대응하면 프로그램이 강제 종료되지 않고 계속해서 코드를 실행시킬 수 있음

```
try{
    // 실행할 코드
}catch(err){
    // try 블록에서 에러가 발생하면 이 코드 블록이 실행
    // err에는 try에서 발생한 Error 객체가 전달
}finally{
    // 에러 발생과 상관없이 반드시 한 번 실행
}
```

- Error 객체
  - Error 생성자 함수에는 에러 메시지를 인수로 전달 가능
- throw문
  - 에러를 발생시키려면 try 코드 블록에서 throw문으로 에러 객체를 던져야 함
  - 에러를 던지면 catch 코드 블록이 실행됨
  - throw된 에러를 어디에서도 캐치하지 않으면 프로그램은 강제 종료됨
